import Head from "next/head";
import HomeBanner from "@/components/HomeBanner";
import ImageCollage from "@/components/ImageCollage1";
import PopularTourOne from "@/components/PopularTourOne";
import PopularTourTwo from "@/components/PopularTourTwo";
import ParallaxBanner from "@/components/ParallaxBanner";
import ParallaxBannerTwo from "@/components/ParallaxBannerTwo";
import Tab from "@/components/Tab";
import Guides from "@/components/Guides";
import Loading from "@/components/Loading";

// Import Swiper styles
import "swiper/css";
import { useEffect, useState } from "react";

export default function Home() {
  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 1000);
  }, []);

  const [loading, setLoading] = useState(true);
  return (
    <>
      <Head>
        <title>VTravelDemo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {loading ? (
        <Loading />
      ) : (
        <>
          <HomeBanner />
          <ImageCollage />
          <PopularTourOne />
          <PopularTourTwo />
          <ParallaxBanner />
          <Guides />
          {/* <Tab /> */}
          <ParallaxBannerTwo />
        </>
      )}
    </>
  );
}
